spring:
  application:
    name: openai-example

  ai:
    openai:
      api-key: ${CHATGPT_API_KEY}
      base-url: ${CHATGPT_BASE_URL:https://api.openai.com}

telegram:
  token: ${TELEGRAM_BOT_TOKEN}
  botName: ${TELEGRAM_BOT_NAME}
